window.Modernizr=function(au,at,ar){function S(b){al.cssText=b;}function R(d,c){return S(ah.join(d+";")+(c||""));
}function Q(d,c){return typeof d===c;}function P(d,c){return !!~(""+d).indexOf(c);}function O(f,c){for(var h in f){var g=f[h];
if(!P(g,"-")&&al[g]!==ar){return c=="pfx"?g:!0;}}return !1;}function N(g,c,j){for(var i in g){var h=c[g[i]];
if(h!==ar){return j===!1?g[i]:Q(h,"function")?h.bind(j||c):h;}}return !1;}function M(g,f,j){var i=g.charAt(0).toUpperCase()+g.slice(1),h=(g+" "+af.join(i+" ")+i).split(" ");
return Q(f,"string")||Q(f,"undefined")?O(h,f):(h=(g+" "+ae.join(i+" ")+i).split(" "),N(h,f,j));}function L(){ap.inputtypes=function(b){for(var l=0,k,j,f,c=b.length;
l<c;l++){ak.setAttribute("type",j=b[l]),k=ak.type!=="text",k&&(ak.value=aj,ak.style.cssText="position:absolute;visibility:hidden;",/^range$/.test(j)&&ak.style.WebkitAppearance!==ar?(ao.appendChild(ak),f=at.defaultView,k=f.getComputedStyle&&f.getComputedStyle(ak,null).WebkitAppearance!=="textfield"&&ak.offsetHeight!==0,ao.removeChild(ak)):/^(search|tel)$/.test(j)||(/^(url|email)$/.test(j)?k=ak.checkValidity&&ak.checkValidity()===!1:k=ak.value!=aj)),ab[b[l]]=!!k;
}return ab;}("search tel url email datetime date month week time datetime-local number range color".split(" "));
}var aq="2.8.3",ap={},ao=at.documentElement,an="modernizr",am=at.createElement(an),al=am.style,ak=at.createElement("input"),aj=":)",ai={}.toString,ah=" -webkit- -moz- -o- -ms- ".split(" "),ag="Webkit Moz O ms",af=ag.split(" "),ae=ag.toLowerCase().split(" "),ad={svg:"http://www.w3.org/2000/svg"},ac={},ab={},aa={},Z=[],Y=Z.slice,X,W=function(v,u,t,s){var r,q,p,o,g=at.createElement("div"),f=at.body,b=f||at.createElement("body");
if(parseInt(t,10)){while(t--){p=at.createElement("div"),p.id=s?s[t]:an+(t+1),g.appendChild(p);}}return r=["&#173;",'<style id="s',an,'">',v,"</style>"].join(""),g.id=an,(f?g:b).innerHTML+=r,b.appendChild(g),f||(b.style.background="",b.style.overflow="hidden",o=ao.style.overflow,ao.style.overflow="hidden",ao.appendChild(b)),q=u(g,v),f?g.parentNode.removeChild(g):(b.parentNode.removeChild(b),ao.style.overflow=o),!!q;
},V=function(){function c(h,g){g=g||at.createElement(b[h]||"div"),h="on"+h;var a=h in g;return a||(g.setAttribute||(g=at.createElement("div")),g.setAttribute&&g.removeAttribute&&(g.setAttribute(h,""),a=Q(g[h],"function"),Q(g[h],"undefined")||(g[h]=ar),g.removeAttribute(h))),g=null,a;
}var b={select:"input",change:"input",submit:"form",reset:"form",error:"img",load:"img",abort:"img"};
return c;}(),U={}.hasOwnProperty,T;!Q(U,"undefined")&&!Q(U.call,"undefined")?T=function(d,c){return U.call(d,c);
}:T=function(d,c){return c in d&&Q(d.constructor.prototype[c],"undefined");},Function.prototype.bind||(Function.prototype.bind=function(a){var h=this;
if(typeof h!="function"){throw new TypeError;}var g=Y.call(arguments,1),f=function(){if(this instanceof f){var b=function(){};
b.prototype=h.prototype;var d=new b,c=h.apply(d,g.concat(Y.call(arguments)));return Object(c)===c?c:d;
}return h.apply(a,g.concat(Y.call(arguments)));};return f;}),ac.cssanimations=function(){return M("animationName");
},ac.video=function(){var b=at.createElement("video"),f=!1;try{if(f=!!b.canPlayType){f=new Boolean(f),f.ogg=b.canPlayType('video/ogg; codecs="theora"').replace(/^no$/,""),f.h264=b.canPlayType('video/mp4; codecs="avc1.42E01E"').replace(/^no$/,""),f.webm=b.canPlayType('video/webm; codecs="vp8, vorbis"').replace(/^no$/,"");
}}catch(e){}return f;},ac.localstorage=function(){try{return localStorage.setItem(an,an),localStorage.removeItem(an),!0;
}catch(b){return !1;}},ac.svg=function(){return !!at.createElementNS&&!!at.createElementNS(ad.svg,"svg").createSVGRect;
};for(var K in ac){T(ac,K)&&(X=K.toLowerCase(),ap[X]=ac[K](),Z.push((ap[X]?"":"no-")+X));}return ap.input||L(),ap.addTest=function(e,c){if(typeof e=="object"){for(var f in e){T(e,f)&&ap.addTest(f,e[f]);
}}else{e=e.toLowerCase();if(ap[e]!==ar){return ap;}c=typeof c=="function"?c():c,typeof enableClasses!="undefined"&&enableClasses&&(ao.className+=" "+(c?"":"no-")+e),ap[e]=c;
}return ap;},S(""),am=ak=null,ap._version=aq,ap._prefixes=ah,ap._domPrefixes=ae,ap._cssomPrefixes=af,ap.hasEvent=V,ap.testProp=function(b){return O([b]);
},ap.testAllProps=M,ap.testStyles=W,ap.prefixed=function(e,d,f){return d?M(e,d,f):M(e,"pfx");},ap;}(this,this.document);
